### ISSUE TITLE
Combining bucket configurations and then modifying causes bucket to be deleted

### ISSUE THREAD

**Issue by brianheuston** [clouddrove/terraform-aws-s3#4]
Terraform version: Terraform v0.12.18

Prereqs for code example: set up logging bucket with logging role proper permissions

module "s3_bucket" {
  source                  = "git@github.com:clouddrove/terraform-aws-s3?ref=tags/0.12.3"
  name                    = "logging-bucket-testname"
  region                  = "us-east-1"
  application             = "clouddrove"
  environment             = "test"
  label_order             = ["environment", "application", "name"]
  versioning              = true
  acl                     = "private"
  bucket_logging_enabled  = true
  target_bucket           = "testname-logs"
  target_prefix           = "logs"
  encryption_enabled      = true
  sse_algorithm           = "AES256"
}

Steps to reproduce:

1. Apply Terraform snippet above. It'll create a bucket that has both logging enabled and encryption enabled.
2. Set encryption_enabled to false
3.  Plan Terraform snippet with encryption_enabled set to false

Expected: Bucket will exist after applying
Actual: Bucket is marked for deletion

It seems like this is happening because on modification, the code will set the count of buckets to 0 in the encryption case. Because the buckets are different in the TF code but have the same name, the bucket will be marked for deletion.

**Comment by anmolnagpal** [comment]
@brianheuston Thanks for reporting this, we have deployed the fix, please check example
